#!/usr/bin/bash
swaylock -C "$HOME/.config/swaylock/config" \
--inside-wrong-color f38ba8 \
--ring-wrong-color 11111b \
--inside-clear-color 89b4fa \
--ring-clear-color 11111b \
--inside-ver-color a6e3a1 \
--ring-ver-color 11111b \
--effect-blur 10x7 \
--effect-vignette 0.2:0.2 \
--ring-color 11111b \
#--key-hl-color f5c2e7 \
--line-color 313244 \
#--inside-color 0011111b \
--separator-color 00000000 \
--fade-in 0.1 &

